version: '3.8'

services:
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    container_name: turkcell-backend
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - CSV_DIR=/app/data
      - LOG_LEVEL=info
    volumes:
      - ./Backend/data:/app/data:ro
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    networks:
      - turkcell-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: turkcell-frontend
    ports:
      - "80:80"
    depends_on:
      backend:
        condition: service_healthy
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
    restart: unless-stopped
    networks:
      - turkcell-network

networks:
  turkcell-network:
    driver: bridge

volumes:
  app-data:
